# version: '3.8'

# services:
#   nextjs:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000" 

#   nginx:
#     image: nginx:latest
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#       - /etc/letsencrypt:/etc/letsencrypt 
#     ports:
#       - "80:80"
#       - "443:443"
#     depends_on:
#       - nextjs
version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000" # Internal port for NGINX

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs 
